"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

from corsheaders.defaults import default_headers
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-+kh8+(+yt5%-io_upre(4r2&ax5emcmt2x#1*t5k8g3(z9!p=r")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() == "true"

def env_list(name, default=""):
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "testserver",
    ".trycloudflare.com",
    ".ngrok-free.app",
    ".ngrok.app",
    ".ngrok.io",
    *env_list("DJANGO_ALLOWED_HOSTS"),
]

EXTERNAL_API_KEYS = {
    "DATA_GO_KR_SERVICE_KEY": os.getenv("DATA_GO_KR_SERVICE_KEY", ""),
    "FINLIFE_API_KEY": os.getenv("FINLIFE_API_KEY", ""),
    "YOUTH_POLICY_API_KEY": os.getenv("YOUTH_POLICY_API_KEY", ""),
    "KAKAO_REST_API_KEY": os.getenv("KAKAO_REST_API_KEY", ""),
    "YOUTUBE_API_KEY": os.getenv("YOUTUBE_API_KEY", ""),
    "KOREAEXIM_API_KEY": os.getenv("KOREAEXIM_API_KEY", ""),
    "METALS_DEV_API_KEY": os.getenv("METALS_DEV_API_KEY", ""),
    "BOK_ECOS_API_KEY": os.getenv("BOK_ECOS_API_KEY", ""),
    "KRX_API_KEY": os.getenv("KRX_API_KEY", ""),
}

AI_SETTINGS = {
    "PROVIDER": os.getenv("AI_PROVIDER", "gms_openai"),
    "MODEL": os.getenv("AI_MODEL", "gpt-4.1"),
    "OPENAI_API_KEY": os.getenv("OPENAI_API_KEY", ""),
    "OPENAI_BASE_URL": os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1"),
    "OPENAI_CHAT_PATH": os.getenv("OPENAI_CHAT_PATH", "/chat/completions"),
    "GMS_API_KEY": os.getenv("GMS_API_KEY", os.getenv("OPENAI_API_KEY", "")),
    "GMS_OPENAI_BASE_URL": os.getenv("GMS_OPENAI_BASE_URL", "https://gms.ssafy.io/gmsapi/api.openai.com/v1"),
    "GMS_OPENAI_CHAT_PATH": os.getenv("GMS_OPENAI_CHAT_PATH", "/chat/completions"),
    "REQUEST_TIMEOUT": int(os.getenv("AI_REQUEST_TIMEOUT", "30")),
    "ENABLE_LLM_EXTRACTION": os.getenv("AI_ENABLE_LLM_EXTRACTION", "true").lower() == "true",
    "ENABLE_LLM_CHAT": os.getenv("AI_ENABLE_LLM_CHAT", "true").lower() == "true",
}

FIRSTHOME_FIXTURE_FALLBACK = {
    "ENABLE_SUPPLEMENT": os.getenv("FIRSTHOME_ENABLE_FIXTURE_SUPPLEMENT", "true").lower() == "true",
    "MATERIALIZE_ON_READ": os.getenv("FIRSTHOME_MATERIALIZE_FIXTURE_ON_READ", "false").lower() == "true",
    "MIN_ACTIVE_SERVICE_NOTICES_PER_REGION": int(os.getenv("FIRSTHOME_MIN_ACTIVE_SERVICE_NOTICES_PER_REGION", "5")),
    "MIN_SERVICE_NOTICES": int(os.getenv("FIRSTHOME_MIN_SERVICE_NOTICES", "5")),
}

FIRSTHOME_CACHE_TIMEOUTS = {
    "RECOMMENDATIONS": int(os.getenv("FIRSTHOME_RECOMMENDATION_CACHE_SECONDS", "300")),
    "MAP": int(os.getenv("FIRSTHOME_MAP_CACHE_SECONDS", "60")),
    "FUNDING": int(os.getenv("FIRSTHOME_FUNDING_CACHE_SECONDS", "300")),
    "MATCHERS": int(os.getenv("FIRSTHOME_MATCHER_CACHE_SECONDS", "300")),
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "firsthome-local-cache",
        "OPTIONS": {
            "MAX_ENTRIES": 1000,
            "CULL_FREQUENCY": 3,
        },
    }
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    *env_list("CORS_ALLOWED_ORIGINS"),
]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.trycloudflare\.com$",
    r"^https://.*\.ngrok-free\.app$",
    r"^https://.*\.ngrok\.app$",
    r"^https://.*\.ngrok\.io$",
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = (
    *default_headers,
    "x-firsthome-client-id",
)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://*.trycloudflare.com",
    "https://*.ngrok-free.app",
    "https://*.ngrok.app",
    "https://*.ngrok.io",
    *env_list("CSRF_TRUSTED_ORIGINS"),
]
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "false").lower() == "true"
CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", SESSION_COOKIE_SAMESITE)
CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", str(SESSION_COOKIE_SECURE)).lower() == "true"

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.profiles.authentication.CsrfExemptSessionAuthentication",
    ],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "FirstHome Navigator API",
    "DESCRIPTION": "Backend API for housing notices, recommendations, funding plans, maps, and AI coach features.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "TAGS": [
        {"name": "Auth / Account", "description": "회원가입, 로그인, 로그아웃, 현재 사용자와 계정 상태 API입니다."},
        {"name": "Profile", "description": "사용자 청약 조건, 관심 항목, 현재 선택 공고/옵션 상태 API입니다."},
        {"name": "Housing Notices", "description": "LH 청약 공고 목록, 상세, 지도 표시용 공고 API입니다."},
        {"name": "Notice Documents", "description": "공식 공고문 발견/분석, 주택형 옵션, 자격 체크리스트 API입니다."},
        {"name": "Recommendations", "description": "청약, 금융상품, 주택담보대출, 정책 추천 API입니다."},
        {"name": "Funding", "description": "선택 공고와 주택형 옵션 기준 자금 로드맵 API입니다."},
        {"name": "AI Coach", "description": "SSAFY GMS/OpenAI-compatible LLM 기반 AI 코치와 전역 챗봇 API입니다."},
        {"name": "Financial Products", "description": "금융상품 목록/상세, 가입상품 저장과 해제 API입니다."},
        {"name": "Market", "description": "Economy NOW 시장 지표와 주거 시장 보조 지표 API입니다."},
        {"name": "Map / Places", "description": "Kakao Local REST API와 Kakao 길찾기 기반 주변 은행, 부동산, 경로 API입니다."},
        {"name": "Community", "description": "청약 아고라 게시글과 댓글 API입니다."},
        {"name": "Videos", "description": "YouTube 기반 청약 관련 영상 검색 API입니다."},
    ],
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "displayOperationId": False,
        "defaultModelsExpandDepth": 1,
        "defaultModelExpandDepth": 2,
        "docExpansion": "none",
        "filter": True,
        "operationsSorter": "alpha",
        "tagsSorter": "alpha",
    },
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    "rest_framework",
    "corsheaders",
    "drf_spectacular",

    # Local apps
    "apps.profiles.apps.ProfilesConfig",
    "apps.notices",
    "apps.notice_docs",
    "apps.recommendations",
    "apps.funding",
    "apps.products",
    "apps.policies",
    "apps.ai_coach",
    "apps.market",
    "apps.videos",
    "apps.community",
    "apps.places",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "false").lower() == "true"

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 20,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = "profiles.CustomUser"
