# Generated by Django 5.0.6 on 2026-06-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousingNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('provider', models.CharField(max_length=60)),
                ('region', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=80)),
                ('supply_type', models.CharField(max_length=40)),
                ('housing_type', models.CharField(max_length=40)),
                ('area', models.CharField(blank=True, max_length=20)),
                ('price', models.PositiveIntegerField(default=0)),
                ('contract_rate', models.FloatField(default=0.1)),
                ('application_deadline', models.DateField()),
                ('winner_date', models.DateField(blank=True, null=True)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('move_in', models.CharField(blank=True, max_length=20)),
                ('competition', models.CharField(blank=True, max_length=40)),
                ('source_url', models.URLField(blank=True)),
                ('location_label', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geocode_quality', models.CharField(blank=True, max_length=24)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('cautions', models.JSONField(blank=True, default=list)),
                ('source_meta', models.JSONField(blank=True, default=dict)),
                ('ownership_type', models.CharField(choices=[('unknown', 'Unknown'), ('public_sale', 'Public sale'), ('newlywed_public_sale', 'Newlywed public sale'), ('private_participation_public_sale', 'Private participation public sale'), ('excluded', 'Excluded')], db_index=True, default='unknown', max_length=40)),
                ('is_service_target', models.BooleanField(db_index=True, default=False)),
                ('exclude_reason', models.CharField(blank=True, max_length=160)),
                ('official_document_status', models.CharField(choices=[('not_requested', 'Not requested'), ('pending', 'Pending'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='not_requested', max_length=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
