# Generated by Django 5.2.14 on 2026-05-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousingNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('provider', models.CharField(max_length=60)),
                ('region', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=80)),
                ('supply_type', models.CharField(max_length=40)),
                ('housing_type', models.CharField(max_length=40)),
                ('area', models.CharField(blank=True, max_length=20)),
                ('price', models.PositiveIntegerField(default=0)),
                ('contract_rate', models.FloatField(default=0.1)),
                ('application_deadline', models.DateField()),
                ('winner_date', models.DateField(blank=True, null=True)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('move_in', models.CharField(blank=True, max_length=20)),
                ('competition', models.CharField(blank=True, max_length=40)),
                ('source_url', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('cautions', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
