# Generated by Django 5.2.14 on 2026-05-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingnotice',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
