# Generated by Django 5.2.14 on 2026-05-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_housingnotice_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingnotice',
            name='source_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
