# Generated by Django 5.0.6 on 2026-05-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_housingnotice_source_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingnotice',
            name='exclude_reason',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='housingnotice',
            name='is_service_target',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='housingnotice',
            name='official_document_status',
            field=models.CharField(choices=[('not_requested', 'Not requested'), ('pending', 'Pending'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='not_requested', max_length=24),
        ),
        migrations.AddField(
            model_name='housingnotice',
            name='ownership_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('public_sale', 'Public sale'), ('newlywed_public_sale', 'Newlywed public sale'), ('private_participation_public_sale', 'Private participation public sale'), ('excluded', 'Excluded')], db_index=True, default='unknown', max_length=40),
        ),
    ]
