# Generated by Django 5.2.14 on 2026-05-19 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('birth_year', models.PositiveSmallIntegerField(default=1999)),
                ('job_status', models.CharField(blank=True, default='employed', max_length=40)),
                ('annual_income', models.PositiveIntegerField(default=0)),
                ('asset', models.PositiveIntegerField(default=0)),
                ('debt', models.PositiveIntegerField(default=0)),
                ('monthly_saving', models.PositiveIntegerField(default=0)),
                ('is_homeless', models.BooleanField(default=True)),
                ('subscription_months', models.PositiveSmallIntegerField(default=0)),
                ('special_conditions', models.JSONField(blank=True, default=list)),
                ('preferred_regions', models.JSONField(blank=True, default=list)),
                ('preferred_supply_types', models.JSONField(blank=True, default=list)),
                ('target_months', models.PositiveSmallIntegerField(default=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_type', models.CharField(choices=[('notice', 'Notice'), ('product', 'Product'), ('policy', 'Policy')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'favorite_type', 'object_id'), name='unique_user_favorite')],
            },
        ),
    ]
