# Generated by Django 5.2.14 on 2026-05-20 02:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_favorite_client_id_favorite_unique_client_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_client_favorite',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('client_id', 'favorite_type', 'object_id'), name='unique_client_favorite'),
        ),
    ]
