# Generated by Django 5.0.6 on 2026-05-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_favorite_unique_client_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desired_area_max_m2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='desired_area_min_m2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='desired_price_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='desired_price_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_down_payment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_payment_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
