# Generated by Django 5.2.14 on 2026-05-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_desired_area_max_m2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favorite_type',
            field=models.CharField(choices=[('notice', 'Notice'), ('option', 'Unit option'), ('product', 'Product'), ('policy', 'Policy')], max_length=20),
        ),
    ]
