# Generated by Django 5.2.14 on 2026-05-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('notice', 'Housing notice'), ('policy', 'Youth policy'), ('product', 'Financial product'), ('document', 'Document')], db_index=True, max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('source_title', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('extraction_type', models.CharField(choices=[('housing_notice', 'Housing notice fields'), ('youth_policy', 'Youth policy fields'), ('financial_product', 'Financial product fields'), ('generic_document', 'Generic document fields')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('prompt_version', models.CharField(default='firsthome-extract-v1', max_length=40)),
                ('input_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('confidence', models.JSONField(blank=True, default=dict)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['source_type', 'source_id', 'extraction_type'], name='ai_coach_ai_source__1bacbf_idx'), models.Index(fields=['status', 'updated_at'], name='ai_coach_ai_status_b1b651_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_id__isnull', False), models.Q(('input_hash', ''), _negated=True)), fields=('source_type', 'source_id', 'extraction_type', 'input_hash'), name='unique_ai_extraction_input')],
            },
        ),
    ]
