# Generated by Django 5.0.6 on 2026-06-22 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_coach', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aicoachplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_coach_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiextractionresult',
            index=models.Index(fields=['source_type', 'source_id', 'extraction_type'], name='ai_coach_ai_source__1bacbf_idx'),
        ),
        migrations.AddIndex(
            model_name='aiextractionresult',
            index=models.Index(fields=['status', 'updated_at'], name='ai_coach_ai_status_b1b651_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiextractionresult',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False), models.Q(('input_hash', ''), _negated=True)), fields=('source_type', 'source_id', 'extraction_type', 'input_hash'), name='unique_ai_extraction_input'),
        ),
        migrations.AddIndex(
            model_name='aicoachplan',
            index=models.Index(fields=['user', 'notice_id', 'option_id', 'input_hash'], name='ai_coach_ai_user_id_313368_idx'),
        ),
        migrations.AddConstraint(
            model_name='aicoachplan',
            constraint=models.UniqueConstraint(fields=('user', 'notice_id', 'option_id', 'input_hash'), name='unique_ai_coach_plan_input'),
        ),
    ]
