# Generated by Django 5.0.6 on 2026-05-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_coach', '0002_aichatlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatlog',
            name='estimated_cost_krw',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aichatlog',
            name='latency_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aichatlog',
            name='prompt_chars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aichatlog',
            name='response_chars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
