# Generated by Django 5.0.6 on 2026-06-05 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_coach', '0003_aichatlog_estimated_cost_krw_aichatlog_latency_ms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiCoachPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_id', models.PositiveIntegerField(db_index=True)),
                ('option_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(default='template', max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_coach_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['user', 'notice_id', 'option_id', 'input_hash'], name='ai_coach_ai_user_id_313368_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='aicoachplan',
            constraint=models.UniqueConstraint(fields=('user', 'notice_id', 'option_id', 'input_hash'), name='unique_ai_coach_plan_input'),
        ),
    ]
