# Generated by Django 5.2.14 on 2026-05-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouthPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(max_length=60)),
                ('target', models.CharField(max_length=160)),
                ('benefit', models.TextField(blank=True)),
                ('policy_category', models.CharField(blank=True, max_length=40)),
                ('regions', models.JSONField(blank=True, default=list)),
                ('age_min', models.PositiveSmallIntegerField(default=19)),
                ('age_max', models.PositiveSmallIntegerField(default=39)),
                ('max_income', models.PositiveIntegerField(default=0)),
                ('requires_homeless', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
