# Generated by Django 5.0.6 on 2026-06-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(db_index=True, max_length=40)),
                ('base_date', models.DateField(db_index=True)),
                ('price', models.FloatField(default=0)),
                ('change_rate', models.FloatField(default=0)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('source_meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['base_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='marketassetprice',
            constraint=models.UniqueConstraint(fields=('asset_type', 'base_date'), name='unique_market_asset_price'),
        ),
    ]
