import { createApp } from 'vue';
import { createPinia } from 'pinia';
import App from './App.vue';
import { router } from './router';
import './style.css';
const savedTheme = localStorage.getItem('firsthome-theme') === 'light' ? 'light' : 'dark';
document.documentElement.dataset.theme = savedTheme;
document.documentElement.style.colorScheme = savedTheme;
const app = createApp(App);
app.use(createPinia());
app.use(router);
app.mount('#app');
