# Generated by Django 5.2.14 on 2026-05-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=40)),
                ('rate', models.CharField(blank=True, max_length=40)),
                ('monthly_limit', models.PositiveIntegerField(default=0)),
                ('term_months', models.PositiveSmallIntegerField(default=0)),
                ('protection_status', models.BooleanField(default=True)),
                ('source_url', models.URLField(blank=True)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
