# Generated by Django 5.0.6 on 2026-06-22 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=40)),
                ('rate', models.CharField(blank=True, max_length=40)),
                ('monthly_limit', models.PositiveIntegerField(default=0)),
                ('term_months', models.PositiveSmallIntegerField(default=0)),
                ('protection_status', models.BooleanField(default=True)),
                ('source_url', models.URLField(blank=True)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('product_code', models.CharField(blank=True, db_index=True, max_length=80)),
                ('bank_code', models.CharField(blank=True, max_length=40)),
                ('join_way', models.TextField(blank=True)),
                ('special_condition', models.TextField(blank=True)),
                ('source_meta', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_trm', models.PositiveSmallIntegerField(default=0)),
                ('intr_rate_type', models.CharField(blank=True, max_length=40)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=80)),
                ('intr_rate', models.FloatField(default=0)),
                ('intr_rate2', models.FloatField(default=0)),
                ('rsrv_type', models.CharField(blank=True, max_length=40)),
                ('rsrv_type_nm', models.CharField(blank=True, max_length=80)),
                ('source_meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['save_trm', '-intr_rate2', '-intr_rate', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('provider', models.CharField(max_length=80)),
                ('category', models.CharField(default='주택담보대출', max_length=40)),
                ('loan_purpose', models.CharField(default='purchase', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('rate', models.CharField(blank=True, max_length=80)),
                ('limit', models.CharField(blank=True, max_length=120)),
                ('limit_amount', models.PositiveBigIntegerField(default=0)),
                ('term', models.CharField(blank=True, max_length=80)),
                ('term_years', models.PositiveSmallIntegerField(default=30)),
                ('age_min', models.PositiveSmallIntegerField(default=19)),
                ('age_max', models.PositiveSmallIntegerField(default=70)),
                ('max_income', models.PositiveBigIntegerField(default=0)),
                ('max_price', models.PositiveBigIntegerField(default=0)),
                ('max_area_m2', models.FloatField(default=0)),
                ('requires_homeless', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('caveats', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserJoinedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('memo', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-joined_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='financialproduct',
            constraint=models.UniqueConstraint(fields=('provider', 'name', 'category'), name='unique_financial_product'),
        ),
        migrations.AddField(
            model_name='financialproductoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.financialproduct'),
        ),
        migrations.AddConstraint(
            model_name='loanproduct',
            constraint=models.UniqueConstraint(fields=('provider', 'name', 'category'), name='unique_loan_product'),
        ),
        migrations.AddField(
            model_name='userjoinedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_users', to='products.financialproduct'),
        ),
        migrations.AddField(
            model_name='userjoinedproduct',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_users', to='products.financialproductoption'),
        ),
    ]
