# Generated by Django 5.0.6 on 2026-06-22 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userjoinedproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='financialproductoption',
            constraint=models.UniqueConstraint(fields=('product', 'save_trm', 'intr_rate_type', 'rsrv_type'), name='unique_financial_product_option'),
        ),
        migrations.AddConstraint(
            model_name='userjoinedproduct',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_joined_product'),
        ),
    ]
