# Generated by Django 5.0.6 on 2026-06-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('provider', models.CharField(max_length=80)),
                ('category', models.CharField(default='주택담보대출', max_length=40)),
                ('loan_purpose', models.CharField(default='purchase', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('rate', models.CharField(blank=True, max_length=80)),
                ('limit', models.CharField(blank=True, max_length=120)),
                ('limit_amount', models.PositiveBigIntegerField(default=0)),
                ('term', models.CharField(blank=True, max_length=80)),
                ('term_years', models.PositiveSmallIntegerField(default=30)),
                ('age_min', models.PositiveSmallIntegerField(default=19)),
                ('age_max', models.PositiveSmallIntegerField(default=70)),
                ('max_income', models.PositiveBigIntegerField(default=0)),
                ('max_price', models.PositiveBigIntegerField(default=0)),
                ('max_area_m2', models.FloatField(default=0)),
                ('requires_homeless', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('caveats', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='loanproduct',
            constraint=models.UniqueConstraint(fields=('provider', 'name', 'category'), name='unique_loan_product'),
        ),
    ]
