# Generated by Django 5.0.6 on 2026-06-22 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('file_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('file_name', models.CharField(blank=True, max_length=220)),
                ('document_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('pending', 'Pending'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], db_index=True, default='discovered', max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=240)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='notices.housingnotice')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('condition_text', models.TextField()),
                ('evidence_text', models.TextField(blank=True)),
                ('page_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_checklists', to='notices.housingnotice')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_checklists', to='notice_docs.noticedocument')),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NoticeExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.CharField(default='mock-v1', max_length=20)),
                ('status', models.CharField(choices=[('mock', 'Mock'), ('pending', 'Pending'), ('valid', 'Valid'), ('needs_review', 'Needs review'), ('failed', 'Failed')], default='mock', max_length=20)),
                ('confidence', models.FloatField(default=0)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='notice_docs.noticedocument')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='notices.housingnotice')),
            ],
        ),
        migrations.CreateModel(
            name='HousingUnitOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=40)),
                ('exclusive_area_m2', models.FloatField(default=0)),
                ('floor_group', models.CharField(blank=True, max_length=40)),
                ('option_type', models.CharField(default='basic', max_length=40)),
                ('base_price', models.PositiveBigIntegerField(default=0)),
                ('loan_amount', models.PositiveBigIntegerField(default=0)),
                ('balcony_extension_price', models.PositiveBigIntegerField(default=0)),
                ('confidence', models.FloatField(default=0)),
                ('source_page', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_options', to='notices.housingnotice')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_options', to='notice_docs.noticedocument')),
                ('extraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_options', to='notice_docs.noticeextraction')),
            ],
            options={
                'ordering': ['exclusive_area_m2', 'unit_type', 'floor_group', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_path', models.CharField(max_length=160)),
                ('page_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_text', models.TextField()),
                ('confidence', models.FloatField(default=0)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='notice_docs.noticeextraction')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('payment_type', models.CharField(choices=[('application', 'Application'), ('winner', 'Winner'), ('down_payment', 'Down payment'), ('middle_payment', 'Middle payment'), ('final_payment', 'Final payment'), ('installment_payment', 'Installment payment'), ('move_in_balance', 'Move-in balance'), ('loan', 'Loan'), ('other', 'Other')], default='other', max_length=24)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('evidence_text', models.TextField(blank=True)),
                ('unit_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='notice_docs.housingunitoption')),
            ],
            options={
                'ordering': ['sequence', 'due_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='housingunitoption',
            constraint=models.UniqueConstraint(fields=('notice', 'unit_type', 'floor_group', 'option_type'), name='unique_notice_unit_option'),
        ),
    ]
